server:
  port: 80
  servlet:
    context-path: /blog

spring:
  profiles:
    active: dev


  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  # configuration:
    # map-underscore-to-camel-case: true

# 打印SQL
logging:
  level:
    com.infs.blog.mapper : debug
